version: "3.3"
services:
  app:
    image: openjdk:17
    container_name: leisure-link-backend
    ports:
      - "8085:8085"
    volumes:
      - ./target/leisure-link.jar:/target/leisure-link.jar
    depends_on:
      - postgres
    command: java -jar /target/leisure-link.jar
    # Service health check
    healthcheck:
      test: curl -f http://localhost:8085/profile || exit 1
      interval: 1m
      timeout: 10s
      retries: 2

  postgres:
    image: postgis/postgis:13-3.4
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: leisurelink


networks:
  leisure-link:
