version: "3.3"
services:
#  app:
#    image: openjdk:17
#    container_name: leisure-link-backend
#    ports:
#      - "8085:8085" # Port aplikacji
#      - "5005:5005" # Port dla debugowania
#    volumes:
#      - ./target/leisure-link.jar:/target/leisure-link.jar
#    depends_on:
#      - postgres
#    environment:
#      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
#    command: java -jar /target/leisure-link.jar
#    # Service health check
#    healthcheck:
#      test: curl -f http://localhost:8085/profile || exit 1
#      interval: 1m
#      timeout: 10s
#      retries: 2


  adminer:
    image: adminer
    labels:
      - traefik.http.routers.adminer.rule=Host(`adminer.localhost`)

  postgres:
    image: postgis/postgis:15-3.4
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: leisurelink

  proxy:
    image: traefik:v2.10
    ports:
      - 127.0.0.1:80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --providers.docker

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"


networks:
  leisure-link:
