version: "3.3"
services:
  app:
    image: openjdk:17
    container_name: leisure-link-backend
    ports:
      - "8085:8085"
    volumes:
      - ./target/leisure-link.jar:/target/leisure-link.jar
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/leisurelink
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - postgres
    command: java -jar /target/leisure-link.jar
    # Service health check
    healthcheck:
      test: curl -f http://localhost:8085/profile || exit 1
      interval: 1m
      timeout: 10s
      retries: 2


  postgres:
    image: postgres:13
    container_name: postgres-db
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: leisurelink
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    healthcheck:
      test: pg_isready -U postgres
      interval: 1m
      timeout: 10s
      retries: 2


volumes:
  postgres-data:

networks:
  leisure-link:

